version: "3.9"  # optional since v1.27.0
services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    image: go-app-ms:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - web

networks: 
  web: 